### ISSUE TITLE
Current season should not be hard-coded

### ISSUE THREAD

**Issue by gfrenoy** [Fllorent0D/Tabt-GraphQL#9]
https://github.com/Fllorent0D/Tabt-GraphQL/blob/6a171ed880fb856084dff9ef25408a33ce14ba7e/src/index.ts#L107

Current season should not be in the code ; maybe in .env but even though, the current season should be calculated from the "seasoninfo" table (based on the start/end date).

**Comment by Fllorent0D** [comment]
Originally I wanted a header (`x-tabt-season`) in order to define the season the request is for.

It is hardcoded for technical reason. Once a resolver wants to fetch some data, it will call a Dataloader. The problem is that those don't have access to the graphql context there are running in. A solution would be to use curried functions when it creates all the dataloaders functions.

I moved it to the .env temporarily 55eb43b4cbe672eb7d026cfd5085ed4625a1033c.

**Comment by Fllorent0D** [comment]
Pushed new HTTP header with the season. You can use `"x-tabt-season": "2019-2020"` as header to specify the season you are requesting for. 
If you don't use the header, the active season is selected by default.
